name: Qodana
on:
  pull_request:
    branches:
      - main
      - production
  push:
    branches:
      - main
      - production

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
