name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches
      - production

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: src/main/java/ca/ulaval/glo2003
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_REPORT_COVERAGE: true
          QODANA_REPORT_SECURITY: true

